easy_admin:
  user:
    #idsplay_name: true
    name_property_path: "name"
  site_name: "<b>FS | Espace d'administration</b>"
  design:
    menu:
      - { label:  'Return to Home', url: '/', rel: 'index', icon: "arrow-alt-circle-left"}
      - label: Clubs
        children:
          - {entity: PlayerClub, label: "Liste des clubs", icon: "th-list"}
          - {entity: PlayerClub, label: "Ajouter un club", icon: "plus", params: {action: new}}
  entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
    PlayerClub:
      class: App\Entity\PlayerClub
      label: Club
